inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

# Notch8 coding conventions
# @see https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
Style/FrozenStringLiteralComment:
  Exclude:
    - spec/test_app/db/schema.rb

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
